# -*- coding: utf-8 -*-
"""TimeTable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHzuRxYPxGjj8qSUKW8Ejd9rRaRSzrr4
"""

"""
Excel Conditional Text Deleter
================================
Reads an Excel file and clears cell content within a specified row/column range
based on user-defined conditions.

Usage:
    python excel_conditional_delete.py

Configuration:
    Edit the CONFIG section below to set your file path, target range, and conditions.
"""

import openpyxl
from openpyxl import load_workbook
from openpyxl.cell.cell import MergedCell

def normalize(text: str, case_sensitive: bool) -> str:
    return text if case_sensitive else text.lower()


def check_condition(cell_value, condition: dict) -> bool:
    ctype = condition["type"]
    cs    = condition.get("case_sensitive", False)

    if ctype == "is_empty":
        return cell_value is None or str(cell_value).strip() == ""

    if cell_value is None:
        return False

    text = str(cell_value)

    if ctype == "contains":
        return normalize(condition["value"], cs) in normalize(text, cs)


    raise ValueError(f"Unknown condition type: '{ctype}'")


def apply_condition_set(cell_value, conditions: list, match_mode: str = "any") -> bool:
    """Return True if the cell should be cleared."""
    results = [check_condition(cell_value, c) for c in conditions]
    if match_mode == "any":
        return any(results)
    if match_mode == "all":
        return all(results)
    raise ValueError("match_mode must be 'any' or 'all'")

def build_merge_map(ws):
    """Returns a dict mapping (row, col) → (master_row, master_col) for every merged cell."""
    merge_map = {}
    for merge_range in ws.merged_cells.ranges:
        master = (merge_range.min_row, merge_range.min_col)
        for row in range(merge_range.min_row, merge_range.max_row + 1):
            for col in range(merge_range.min_col, merge_range.max_col + 1):
                merge_map[(row, col)] = master
    return merge_map

def process_excel(
    input_file:  str,
    output_file: str,
    sheet_name,
    row_start:   int,
    row_end:     int,
    col_start:   int,
    col_end:     int,
    conditions:  list,
    match_mode:  str = "any",
):
    wb = load_workbook(input_file)
    ws = wb[sheet_name] if sheet_name else wb.active

    cleared = 0
    merge_map = build_merge_map(ws)
    already_cleared = set()  # avoid hitting the same master cell twice

    merge_map     = build_merge_map(ws)
    already_seen  = set()   # master coordinates already evaluated
    cleared       = 0

    for row in range(row_start, row_end + 1):
        for col in range(col_start, col_end + 1):
            cell = ws.cell(row=row, column=col)

            if isinstance(cell, MergedCell):
                master_coords = merge_map.get((row, col))
                if not master_coords or master_coords in already_seen:
                    continue
                already_seen.add(master_coords)
                master = ws.cell(*master_coords)
            else:
                if (row, col) in already_seen:
                    continue
                already_seen.add((row, col))
                master = cell

            if not (apply_condition_set(cell.value, conditions[0], match_mode) and apply_condition_set(cell.value, conditions[1], match_mode)):
                print(f"  Clearing {cell.coordinate}  ← was: {repr(cell.value)}")
                master.value = None
                cleared += 1
            else:
                cell_content = master.value
                course_code = cell_content[:8]
                course_name = course_name_from_code(course_code)
                master.value = master.value.replace(course_code, course_name + f"({course_code[:3]})")



    wb.save(output_file)
    print(f"\n✓ Done — {cleared} cell(s) cleared. Saved to '{output_file}'.")

def course_name_from_code(course_code: str) -> str:
    courses = {
        "FIN 6002": {"instructor": "PRS", "name": "Commercial Banking"},
        "FIN 6004": {"instructor": "KPD", "name": "Financial Derivatives"},
        "FIN 6022": {"instructor": "VNG", "name": "Financial Statement Analysis"},
        "FIN 6006": {"instructor": "SJK", "name": "Fixed Income Securities"},
        "FIN 6005": {"instructor": "DPD", "name": "Security Valuation"},
        "ITS 6009": {"instructor": "BSR", "name": "Emerging Technologies for Managers"},
        "ITS 6002": {"instructor": "GRN", "name": "IT Risk Management and Cyber Security"},
        "ITS 6001": {"instructor": "AVK", "name": "Technology Consulting & Business Analysis"},
        "ITS 6007": {"instructor": "AMK", "name": "Digital Transformation"},
        "ITS 6012": {"instructor": "VVJ", "name": "Digital Platform and Technology Ecosystem"},
        "ANT 6009": {"instructor": "KKB", "name": "Data Visualization"},
        "ANT 6010": {"instructor": "KKB", "name": "Foundations of Business Analytics"},
        "MKT 6006": {"instructor": ["SNR", "STY"], "name": "Consumer Behaviour"},
        "MKT 6004": {"instructor": ["JVN", "SLP"], "name": "Brand Management"},
        "MKT 6003": {"instructor": "AKL", "name": "Services Marketing"},
        "MKT 6009": {"instructor": ["SLP", "JYT", "SNR"], "name": "Sales & Distribution Management"},
        "MKT 6005": {"instructor": "SNR", "name": "Digital Marketing"},
    }
    return courses[course_code]["name"]

# ─────────────────────────────────────────────
# CONFIG — edit these values before running
# ─────────────────────────────────────────────

INPUT_FILE  = "input.xlsx"                # Path to the source Excel file
OUTPUT_FILE = "output.xlsx"               # Path to save the modified file (can be same as INPUT_FILE)
SHEET_NAME  = "TERM 4 MBA"                # Sheet name to target, or None for the active sheet

# Row/column bounds (1-indexed, inclusive)
ROW_START   = 9                     # First row to scan (e.g. 2 to skip a header row)
ROW_END     = 53                    # Last row to scan
COL_START   = 3                     # First column to scan (1 = column A)
COL_END     = 10                    # Last column to scan  (5 = column E)

CONDITION_SET_1 = [
    {"type": "contains",     "value": "MKT",  "case_sensitive": True},
    {"type": "contains",     "value": "6001",  "case_sensitive": True},
]

CONDITION_SET_2 = [
    {"type": "contains",     "value": "SA",  "case_sensitive": True},
    {"type": "contains",     "value": "S1",  "case_sensitive": True},
]

CONDITIONS = [
    CONDITION_SET_1,
    CONDITION_SET_2
]


if __name__ == "__main__":
    print(f"Processing '{INPUT_FILE}', sheet={SHEET_NAME or 'active'}")
    print(f"Range: rows {ROW_START}–{ROW_END}, cols {COL_START}–{COL_END}\n")

    process_excel(
        input_file  = INPUT_FILE,
        output_file = OUTPUT_FILE,
        sheet_name  = SHEET_NAME,
        row_start   = ROW_START,
        row_end     = ROW_END,
        col_start   = COL_START,
        col_end     = COL_END,
        conditions  = CONDITIONS,
        match_mode  = "any",   # "any" = clear if ANY condition matches; "all" = ALL must match
    )

